=== sheilnaik/search/api/bangs.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Kagi Bangs Schema",
    "description": "This schema defines the structure for bangs used by Kagi Search",
    "type": "array",
    "items": {
      "type": "object",
      "properties": {
        "s": {
          "type": "string",
          "title": "Website Name",
          "description": "The name of the website associated with the bang."
        },
        "d": {
          "type": "string",
          "title": "Domain",
          "description": "The domain name of the website."
        },
        "t": {
          "type": "string",
          "title": "Trigger",
          "description": "The specific trigger word or phrase used to invoke the bang."
        },
        "u": {
          "type": "string",
          "title": "Template URL",
          "description": "The URL template to use when the bang is invoked, where `{{{s}}}` is replaced by the user's query."
        },
        "c": {
          "type": "string",
          "title": "Category",
          "description": "The category of the website, if applicable.",
          "enum": [
            "Entertainment",
            "Man Page",
            "Multimedia",
            "News",
            "Online Services",
            "Region search",
            "Research",
            "Shopping",
            "Tech",
            "Translation"
          ]
        },
        "sc": {
          "type": "string",
          "title": "Subcategory",
          "description": "The subcategory of the website, if applicable."
        },
        "fmt": {
          "type": "array",
          "title": "Format",
          "description": "The format flags indicating how the query should be processed.",
          "uniqueItems": true,
          "minItems": 0,
          "maxItems": 3,
          "items": {
            "type": "string",
            "enum": [
              "open_base_path",
              "url_encode_placeholder",
              "url_encode_space_to_plus"
            ]
          }
        }
      },
      "required": [
        "d",
        "s",
        "t",
        "u"
      ],
      "additionalProperties": false
    }
  }

=== sheilnaik/search/bangs.json
[
  {
      "s": "YouTube",
      "d": "www.youtube.com",
      "t": "yt",
      "u": "https://www.youtube.com/results?search_query={{{s}}}",
      "c": "Multimedia",
      "sc": "Video"
    },
    {
      "s": "YouTube",
      "d": "www.youtube.com",
      "t": "you",
      "u": "https://www.youtube.com/results?search_query={{{s}}}",
      "c": "Entertainment",
      "sc": "Misc"
    },
    {
      "s": "English Wikipedia",
      "d": "en.wikipedia.org",
      "t": "wiki",
      "u": "https://en.wikipedia.org/w/index.php?search={{{s}}}",
      "c": "Research",
      "sc": "Reference"
    },
    {
      "s": "English Wikipedia",
      "d": "en.wikipedia.org",
      "t": "w",
      "u": "https://en.wikipedia.org/w/index.php?search={{{s}}}",
      "c": "Research",
      "sc": "Reference"
    },
    {
      "s": "Reddit",
      "d": "www.reddit.com",
      "t": "r",
      "u": "https://www.reddit.com/search?q={{{s}}}",
      "c": "Online Services",
      "sc": "Social"
    },
    {
      "s": "Reddit subreddit",
      "d": "www.reddit.com",
      "t": "reddits",
      "u": "http://www.reddit.com/r/{{{s}}}",
      "c": "Online Services",
      "sc": "Social"
    },
    {
      "s": "Reddit subreddit",
      "d": "www.reddit.com",
      "t": "rs",
      "u": "http://www.reddit.com/r/{{{s}}}",
      "c": "Online Services",
      "sc": "Social"
    },
    {
      "s": "Perplexity",
      "d": "www.perplexity.ai",
      "t": "p",
      "u": "https://www.perplexity.ai/?s=o&q={{{s}}}",
      "c": "Research",
      "sc": "Reference"
    },
    {
      "s": "Google Maps",
      "d": "maps.google.com",
      "t": "gm",
      "u": "https://maps.google.com/maps?q={{{s}}}",
      "c": "Online Services",
      "sc": "Google"
    },
    {
      "s": "Google Images",
      "d": "google.com",
      "t": "i",
      "u": "https://google.com/search?tbm=isch&q={{{s}}}&tbs=imgo:1",
      "c": "Online Services",
      "sc": "Google"
    },
    {
      "s": "Google Images",
      "d": "google.com",
      "t": "gi",
      "u": "https://google.com/search?tbm=isch&q={{{s}}}&tbs=imgo:1",
      "c": "Online Services",
      "sc": "Google"
    },
    {
      "s": "Apple Maps",
      "d": "beta.maps.apple.com",
      "t": "am",
      "u": "https://beta.maps.apple.com/?address={{{s}}}",
      "c": "Online Services",
      "sc": "Apple"
    },
    {
      "s": "Amazon.com",
      "d": "www.amazon.com",
      "t": "a",
      "u": "https://www.amazon.com/s?k={{{s}}}",
      "c": "Shopping",
      "sc": "Online"
    },
    {
      "s": "Movies Lens",
      "d": "www.google.com",
      "t": "movies",
      "u": "https://www.google.com/search?q={{{s}}}+site%3Arottentomatoes.com+OR+site%3Ametacritic.com+OR+site%3Awikipedia.org&udm=14",
      "c": "Online Services",
      "sc": "Google"
    },
    {
      "s": "eBay",
      "d": "www.ebay.com",
      "t": "ebay",
      "u": "https://www.ebay.com/sch/items/?_nkw={{{s}}}",
      "c": "Shopping",
      "sc": "Online (marketplace)"
    },
    {
      "s": "Amazon.com",
      "d": "www.amazon.com",
      "t": "a",
      "u": "https://www.amazon.com/s?k={{{s}}}",
      "c": "Shopping",
      "sc": "Online"
    },
    {
      "s": "Amazon.com",
      "d": "www.amazon.com",
      "t": "z",
      "u": "https://www.amazon.com/s?k={{{s}}}",
      "c": "Shopping",
      "sc": "Online"
    },
    {
      "s": "Amazon Kindle",
      "d": "www.amazon.com",
      "t": "kindle",
      "u": "https://www.amazon.com/s?k={{{s}}}&i=digital-text",
      "c": "Multimedia",
      "sc": "Books"
    },
    {
      "s": "Wolfram Alpha",
      "d": "www.wolframalpha.com",
      "t": "wolf",
      "u": "https://www.wolframalpha.com/input?i={{{s}}}",
      "c": "Search",
      "sc": "Search"
    }
]
